# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=4.0.1
FROM docker.io/library/ruby:${RUBY_VERSION}-slim
ARG BUNDLER_VERSION=4.0.3

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      libpq-dev \
      libyaml-dev \
      nodejs \
      npm \
      curl \
      chromium \
      chromium-driver \
      libasound2 \
      libatk1.0-0 \
      libatk-bridge2.0-0 \
      libcups2 \
      libgbm1 \
      libgtk-3-0 \
      libnss3 \
      libpangocairo-1.0-0 \
      libx11-xcb1 \
      libxcomposite1 \
      libxdamage1 \
      libxfixes3 \
      libxkbcommon0 \
      libxrandr2 \
      libxshmfence1 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN corepack enable

WORKDIR /rails

ENV BUNDLE_PATH="/usr/local/bundle"

RUN gem install --no-document bundler:${BUNDLER_VERSION}

CMD ["bash", "-lc", "bin/rails server -b 0.0.0.0"]
