# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=4.0.1
FROM docker.io/library/ruby:${RUBY_VERSION}-slim
ARG BUNDLER_VERSION=4.0.3

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      libpq-dev \
      libyaml-dev \
      curl && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails

ENV BUNDLE_PATH="/usr/local/bundle"

RUN gem install --no-document bundler:${BUNDLER_VERSION}

CMD ["bash", "-lc", "bin/rails server -b 0.0.0.0"]
